"use client";

import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, Brain, CheckCircle2, ChevronRight, FileText, FolderKanban, LayoutDashboard, Lightbulb, Menu, MessageSquare, Mic2, Plus, Search, Sparkles, Target, X } from "lucide-react";

type Tool = { id:string; title:string; description:string; icon:React.ElementType; color:string };
const tools:Tool[] = [
 {id:"idea",title:"Project Idea Generator",description:"Turn interests into realistic, jury-ready PFE/PFA ideas.",icon:Lightbulb,color:"text-amber-300"},
 {id:"research",title:"Research Assistant",description:"Structure your literature review and research questions.",icon:BookOpen,color:"text-blue-300"},
 {id:"report",title:"Report Copilot",description:"Build stronger chapters, methodology and conclusions.",icon:FileText,color:"text-violet-300"},
 {id:"planner",title:"Project Planner",description:"Generate milestones, tasks and a practical roadmap.",icon:Target,color:"text-emerald-300"},
 {id:"defense",title:"Defense Simulator",description:"Practice against an AI jury before the real defense.",icon:Mic2,color:"text-rose-300"},
 {id:"architecture",title:"Architecture Designer",description:"Explore your stack, modules and database structure.",icon:FolderKanban,color:"text-cyan-300"},
];

export default function Home() {
 const [active,setActive]=useState("overview"); const [mobile,setMobile]=useState(false); const [project,setProject]=useState(""); const [created,setCreated]=useState(false);
 const greeting=useMemo(()=>created?`Let's build ${project || "your project"}.` : "Good morning, Ahmed.",[created,project]);
 return <div className="min-h-screen flex">
  <aside className={`${mobile?"fixed inset-y-0 left-0 z-30":"hidden md:flex"} w-64 flex-col border-r border-white/10 bg-[#0a0a0f] p-5`}>
   <div className="flex items-center justify-between mb-8"><div className="flex items-center gap-2 font-bold text-lg"><span className="grid place-items-center w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-indigo-500"><Sparkles size={17}/></span>PFE<span className="text-violet-400">Copilot</span></div>{mobile&&<button onClick={()=>setMobile(false)}><X size={18}/></button>}</div>
   <div className="text-[10px] uppercase tracking-[.18em] text-zinc-500 mb-3">Workspace</div>
   <nav className="space-y-1">{[["overview","Overview",LayoutDashboard],["projects","My Projects",FolderKanban],["tools","AI Tools",Brain]].map(([id,label,Icon])=><button key={id} onClick={()=>{setActive(id as string);setMobile(false)}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm ${active===id?"bg-white/8 text-white":"text-zinc-400 hover:text-white hover:bg-white/5"}`}><Icon size={17}/>{label}</button>)}</nav>
   <div className="mt-auto glass rounded-xl p-4"><div className="flex items-center gap-2 text-sm font-medium"><Sparkles size={15} className="text-violet-400"/> AI Credits</div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-violet-500 to-indigo-400"/></div><div className="mt-2 text-xs text-zinc-500">72 / 100 credits</div></div>
  </aside>
  <main className="flex-1 min-w-0"><header className="h-16 border-b border-white/10 flex items-center justify-between px-5 md:px-8 sticky top-0 bg-[#07070b]/80 backdrop-blur-xl z-20"><button className="md:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="hidden md:block text-sm text-zinc-500">Workspace / <span className="text-zinc-300">Overview</span></div><div className="flex items-center gap-3 ml-auto"><button className="text-zinc-400 hover:text-white"><Search size={18}/></button><div className="w-8 h-8 rounded-full bg-gradient-to-br from-violet-400 to-blue-500 grid place-items-center text-xs font-bold">AN</div></div></header>
   <div className="max-w-6xl mx-auto px-5 md:px-8 py-9 grid-bg min-h-[calc(100vh-64px)]"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><div className="text-xs text-violet-400 font-semibold uppercase tracking-[.18em] mb-3">AI project workspace</div><h1 className="text-3xl md:text-4xl font-semibold tracking-tight">{greeting}</h1><p className="text-zinc-400 mt-2 max-w-xl">Everything you need to go from a rough idea to a confident PFE/PFA defense.</p></div><button onClick={()=>setCreated(true)} className="inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 bg-white text-black font-semibold text-sm hover:bg-zinc-200"><Plus size={17}/> New project</button></div>
   {!created?<section className="mt-8 glass rounded-2xl p-6 md:p-8 overflow-hidden relative"><div className="absolute -right-20 -top-20 w-64 h-64 bg-violet-600/20 blur-3xl rounded-full"/><div className="relative max-w-2xl"><div className="inline-flex items-center gap-2 text-xs text-violet-300 bg-violet-500/10 border border-violet-500/20 rounded-full px-3 py-1.5"><Sparkles size={13}/> Start with your project idea</div><h2 className="text-2xl font-semibold mt-4">What are you building?</h2><p className="text-zinc-400 mt-2">Describe your idea in one sentence. PFE Copilot will turn it into a structured project brief.</p><div className="flex flex-col sm:flex-row gap-2 mt-5"><input value={project} onChange={e=>setProject(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setCreated(true)} placeholder="e.g. AI platform for student mental health" className="flex-1 bg-black/30 border border-white/10 rounded-xl px-4 py-3 outline-none focus:border-violet-500/60 text-sm"/><button onClick={()=>setCreated(true)} className="px-5 py-3 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 font-semibold text-sm flex items-center justify-center gap-2">Create project <ArrowRight size={16}/></button></div></div></section>:<section className="mt-8 glass rounded-2xl p-6"><div className="flex items-start justify-between"><div><div className="text-xs text-emerald-400 uppercase tracking-widest">Project created</div><h2 className="text-xl font-semibold mt-2">{project || "Untitled PFE/PFA"}</h2><p className="text-sm text-zinc-400 mt-1">Your AI workspace is ready. Start by generating a project brief.</p></div><CheckCircle2 className="text-emerald-400"/></div><button onClick={()=>setActive("tools")} className="mt-5 inline-flex items-center gap-2 text-sm text-violet-300 hover:text-violet-200">Open AI tools <ChevronRight size={16}/></button></section>}
   <div className="flex items-center justify-between mt-10 mb-4"><div><h2 className="font-semibold text-lg">AI tools</h2><p className="text-xs text-zinc-500 mt-1">Built around the PFE/PFA journey</p></div><button onClick={()=>setActive("tools")} className="text-xs text-zinc-400 hover:text-white">View all</button></div>
   <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{tools.slice(0,6).map(t=><button key={t.id} onClick={()=>setActive("tools")} className="text-left glass rounded-xl p-5 hover:border-white/20 hover:bg-white/[.045] transition group"><div className="flex items-start justify-between"><span className="w-9 h-9 rounded-lg bg-white/5 grid place-items-center"><t.icon size={18} className={t.color}/></span><ChevronRight size={16} className="text-zinc-600 group-hover:text-zinc-300"/></div><h3 className="font-medium mt-4">{t.title}</h3><p className="text-xs text-zinc-500 leading-5 mt-1">{t.description}</p></button>)}</div>
   <section className="mt-8 grid lg:grid-cols-3 gap-3"><div className="lg:col-span-2 glass rounded-xl p-5"><div className="flex items-center justify-between"><h3 className="font-medium">Project progress</h3><span className="text-xs text-zinc-500">0% complete</span></div><div className="mt-4 h-2 rounded-full bg-white/5"><div className="w-0 h-full rounded-full bg-gradient-to-r from-violet-500 to-indigo-400"/></div><div className="grid grid-cols-4 gap-2 mt-5 text-center">{["Idea","Research","Build","Defense"].map((x,i)=><div key={x} className="rounded-lg bg-white/[.025] p-3"><div className="text-xs text-zinc-500">0{i+1}</div><div className="text-xs mt-1">{x}</div></div>)}</div></div><div className="glass rounded-xl p-5"><div className="flex items-center gap-2"><MessageSquare size={17} className="text-blue-400"/><h3 className="font-medium">AI activity</h3></div><p className="text-sm text-zinc-500 mt-5">No activity yet. Create a project to get started.</p></div></section>
   <footer className="pt-10 pb-4 text-xs text-zinc-600 flex justify-between"><span>PFE Copilot MVP</span><span>Built for students, supervisors & schools</span></footer></div></main>
 </div>
}
